apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "biocontainer-registry.fullname" . }}
  labels:
    app: {{ template "biocontainer-registry.name" . }}
    chart: {{ template "biocontainer-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "biocontainer-registry.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "biocontainer-registry.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: mongo-db-user-creator-init
          image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          env:
            - name: "MONGO_DB"
              value: {{ .Values.mongoConfig.dbName }}
            - name: "MONGODB_PASS"
              value: {{ .Values.mongoConfig.servicePassword }}
            - name: "MONGODB_USER"
              value: {{ .Values.mongoConfig.serviceUsername }}
            - name: "MONGODB_ROLES"
              value: {{ .Values.mongoConfig.roles }}
            - name: "ADMIN_USER"
              value: {{ index .Values "mongodb-replicaset" "auth" "adminUser" }}
            - name: "ADMIN_PASSWORD"
              value: {{ index .Values "mongodb-replicaset" "auth" "adminPassword" }}
            - name: "MONGODB_HOST"
              value: {{ template "mongodb-replicaset.fullname" . }}
          resources:
{{ toYaml .Values.init.resources | indent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
