logging.level:
  root: DEBUG
  org:
    springframework:
      security: DEBUG
      web: ERROR
    hibernate: DEBUG
    apache:
      commons.dbcp2: DEBUG
      http: DEBUG
  sun.rmi: WARN

dockerhub:
  urls:
    containers-list: "https://hub.docker.com/v2/repositories/%%namespace%%/?page_size=100"
    container-details: "https://hub.docker.com/v2/repositories/%%namespace%%/%%container_name%%/"
    container-tags: "https://hub.docker.com/v2/repositories/%%namespace%%/%%container_name%%/tags/?page_size=250"

quay.io:
  urls:
    containers-list: "https://quay.io/api/v1/repository?popularity=true&last_modified=true&public=true&starred=false&namespace=%%namespace%%"
    container-details: "https://quay.io/api/v1/repository/%%namespace%%/%%container_name%%"